### ISSUE TITLE
Tool doesn't generate symlinks for com.unity.rendering-pipelines.* 

### ISSUE THREAD

**Issue by sp4ghet** [hecomi/HLSLToolsForVisualStudioConfigGenerator#1]
Using Unity 2022.2:

```packages-lock.json
    "com.unity.render-pipelines.core": {
      "version": "14.0.4",
      "depth": 1,
      "source": "builtin",
      "dependencies": {
        "com.unity.ugui": "1.0.0",
        "com.unity.modules.physics": "1.0.0",
        "com.unity.modules.terrain": "1.0.0",
        "com.unity.modules.jsonserialize": "1.0.0"
      }
    }
```

You can see that the com.unity.render-pipelines.core package is treated as `builtin`, which is excluded from the generated symlinks.
Many shaders (e.g. post processing effects) will rely on HLSL include files defined in these packages so it is helpful to have them available to HLSLTools. (This also includes shadergraph, HDRP, and URP packages)

I think there are two solutions to this:

1. Enable multiple "Unity Directories" and add `%PROGRAMFILES%\Unity\Hub\Editor\$VERSION\Editor\Data\Resources\PackageManager\BuiltInPackages`  as well as the CGInclude directory. If you are worried about too many packages being symlinked cluttering the ShaderIncludes directory, this solution could be applied multiple times by the user to target specific builtin packages rather than the entire directory.
2. Remove this line: https://github.com/hecomi/HLSLToolsForVisualStudioConfigGenerator/blob/main/Assets/HLSLToolsForVisualStudioConfigGenerator/Editor/HLSLToolsForVisualStudioConfigGenerator.cs#L157 and symlink builtin packages.

I don't really have any strong opinions about which is better but it would be nice to have HDRP and core shaders available to the plugin by default.

**Comment by hecomi** [comment]
Thank you for the info. I would like to consider the following solution.

- Add checkboxes next to the packages listed in the Config Generator window, and only add the selected packages to `shadertoolsconfig.json`.
- Include the builtin packages in the Packages list, but keep them off by default.
- However, CoreRP/URP/HDRP will be whitelisted and turned on by default.

**Comment by sp4ghet** [comment]
That would work for me! 
Personally, I also use ShaderGraph includes quite often when writing custom shader nodes but as long as an easy option to add it exists I would be happy with it not being default.

I can work on a PR if you're preoccupied so please let me know!

**Comment by hecomi** [comment]
Version 1.1.0 with the above changes has been released. Could you please test it when you have time?

<img width="840" alt="image" src="https://user-images.githubusercontent.com/493433/219850609-e67bafc9-b171-42f8-b861-ab0fb0adec65.png">
